import { Plant } from '../types';

export const PLANTS: Plant[] = [
  {
    id: 'artemisia',
    nameRu: 'Полынь горькая',
    nameKk: 'Жусан',
    nameLatin: 'Artemisia absinthium',
    description: 'Серебристые листья с характерным запахом. Самое распространённое растение степи Актобе.',
    whereFound: 'Растёт везде в степи, вдоль дорог, на пустырях',
    ligninPct: 28,
    cellulosePct: 35,
    optimalPyrolysisTemp: 500,
    pyrolysisTempRange: [400, 600],
    knownEfficiency: { Cr: 91, Pb: 88, MP: 79 },
    emoji: '🌿',
    color: '#5A8A3C',
  },
  {
    id: 'phragmites',
    nameRu: 'Камыш обыкновенный',
    nameKk: 'Қамыс',
    nameLatin: 'Phragmites australis',
    description: 'Высокие стебли у воды. Высокое содержание кремнезёма и целлюлозы.',
    whereFound: 'Растёт у воды, по берегам рек и озёр',
    ligninPct: 22,
    cellulosePct: 44,
    optimalPyrolysisTemp: 450,
    pyrolysisTempRange: [350, 550],
    knownEfficiency: { Cr: 87, Pb: 82, MP: 85 },
    emoji: '🌾',
    color: '#8A7A3C',
  },
  {
    id: 'typha',
    nameRu: 'Рогоз широколистный',
    nameKk: 'Рогоз',
    nameLatin: 'Typha latifolia',
    description: 'Коричневые цилиндрические початки у воды.',
    whereFound: 'По берегам водоёмов, болотам',
    ligninPct: 18,
    cellulosePct: 48,
    optimalPyrolysisTemp: 400,
    pyrolysisTempRange: [300, 500],
    knownEfficiency: { Cr: 79, Pb: 75, MP: 80 },
    emoji: '🌱',
    color: '#6B5E2E',
  },
  {
    id: 'wheat_straw',
    nameRu: 'Пшеничная солома',
    nameKk: 'Бидай сабаны',
    nameLatin: 'Triticum aestivum straw',
    description: 'Пожнивные остатки после сбора пшеницы.',
    whereFound: 'На сельхоз полях после уборки урожая',
    ligninPct: 16,
    cellulosePct: 38,
    optimalPyrolysisTemp: 500,
    pyrolysisTempRange: [400, 700],
    knownEfficiency: { Cr: 74, Pb: 78, MP: 68 },
    emoji: '🌾',
    color: '#C4A240',
  },
];
